backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: /static/uploads
public_folder: /uploads
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: '/src/lib/posts/'
    create: true
    slug: '{{slug}}'
    preview_path: 'blog/{{slug}}'
    fields:
      - label: 'Published'
        name: 'date'
        widget: 'datetime'
        date_format: 'YYYY.MM.DD'
        format: 'L'
      - label: 'Updated'
        name: 'updated'
        format: 'L'
        default: ''
        required: false
        widget: 'datetime'
        date_format: 'YYYY.MM.DD'
      - label: 'Featured Image'
        name: 'coverImage'
        widget: 'image'
        required: false
      - label: 'Image Width'
        name: 'coverWidth'
        widget: 'number'
        default: 16
      - label: 'Image Height'
        name: 'coverHeight'
        widget: 'number'
        default: 9
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

site_url: https://podcasting4value.com
display_url: https://podcasting4value.com
# logo_url: https://your-site.com/images/logo.svg
