backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: /static/uploads
public_folder: /uploads
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: '/posts/'
    create: true
    slug: '{{slug}}'
    preview_path: 'blog/{{slug}}'
    fields:
      - label: 'Featured Image'
        name: 'thumbnail'
        widget: 'image'
        required: false
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

site_url: https://podcasting4value.com
display_url: https://podcasting4value.com
# logo_url: https://your-site.com/images/logo.svg
