backend:
  name: git-gateway
  branch: main
collections:
  - name: routes
    label: routes
    folder: src/routes
    create: true
    fields:
      - name: title
      - name: nav_label
      - name: body
        widget: markdown
media_folder: 'static/uploads'
public_folder: '/uploads'

site_url: https://podcasting4value.com
display_url: https://podcasting4value.com
# logo_url: https://your-site.com/images/logo.svg
